# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: db_container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3310:3310

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/node_modules

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080