// Post new user
POST http://localhost:3000/users
Content-type: application/json

{
    "email": "test@mail.com",
    "password": "password"
}

### Get all users
GET http://localhost:3000/users

### Get user by ID
GET http://localhost:3000/users/1

### Update user
PATCH http://localhost:3000/users/1
Content-type: application/json

{
    "password": "password"
}

### Login user 
// Should return pair of tokens - access one with expire time defined in env file, 
// and refresh token used to generate access one after expire time
POST http://localhost:3000/login
Content-type: application/json

{
    "email": "test@mail.com",
    "password": "password"
}

### Get new access token 
// Send refresh token to regenerate new access token
POST http://localhost:3000/refresh-token
Content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJpYXQiOjE2OTE1NzYyNDN9.OMcFU27GKJpLRhhQFDAA1L8swOS1X9T9n2qKikgTtwA"
}

### Get protected resource
// pass access token in authorization header
GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJpYXQiOjE2OTE2NTk5NTcsImV4cCI6MTY5MTY2MTc1N30.sXQVDVa2SV1AMcmwV3iHkeksIG02R92oHdDDIrdbbg8

### Logout
// Pass refresh token to logout and remove token on server
POST http://localhost:3000/logout
Content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJpYXQiOjE2OTE2NjE0NDN9.UDQCNFSWpv71lxHM2w_G3GK-Q4m1wUXfMsYSt2DUkPY"
}